### ISSUE TITLE
SQL error: Your request cannot be completed because of the failure of an external dependency. Please try again later., SQL state XX000 in SQLExecute

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/ex-snowflake-query-history#9]
```
Fetching query history from keboola.ap-southeast-2.snowflakecomputing.com
Fetching queries completed after 2019-01-19 16:12:15.488 (UTC) set by last execution.
odbc_execute(): SQL error: Your request cannot be completed because of the failure of an external dependency. Please try again later., 
SQL state XX000 in SQLExecute
#0 [internal function]: {closure}(2, 'odbc_execute():...', '/code/vendor/ke...', 178, Array)
#1 /code/vendor/keboola/php-csv-db-import/src/Snowflake/Connection.php(178): odbc_execute(Resource id #89, Array)
#2 /code/src/Keboola/SnowflakeQueryHistory/Fetcher.php(69): Keboola\Db\Import\Snowflake\Connection->fetchAll('select  \n ...')
#3 /code/src/Keboola/SnowflakeQueryHistory/RunCommand.php(124): Keboola\SnowflakeQueryHistory\Fetcher->fetchHistory(Object(Closure), Array)
#4 /code/src/Keboola/SnowflakeQueryHistory/RunCommand.php(39): Keboola\SnowflakeQueryHistory\RunCommand->runExtraction(Object(Symfony\Component\Console\Output\ConsoleOutput), '/data/')
#5 /code/vendor/symfony/console/Command/Command.php(255): Keboola\SnowflakeQueryHistory\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /code/vendor/symfony/console/Application.php(953): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /code/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Keboola\SnowflakeQueryHistory\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /code/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /code/src/app.php(17): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 {main}
```

Stalo se to v AP regionu, nemůže to být tím?

https://connection.keboola.com/admin/utils/logs?file=2019/01/19/18/2019-01-19-18-13-39-5c435ac3c08c4-exception

https://connection.keboola.com/admin/utils/logs?file=2019/01/19/18/2019-01-19-18-13-39-5c435ac3c5276-log

**Comment by Halama** [comment]
Vypnu to pro AP at to zbytečně nestartuje WH.

**Comment by ondrejhlavacek** [comment]
Jo aha! Takže to je tím, že čeká na startující WH?

**Comment by Halama** [comment]
jako bude to nějaká interní chyba snsflk takže bych to neřešil a zavřel. To že to zařvalo je vlastně správně.

**Comment by Halama** [comment]
V transformaci jsem to disabloval https://connection.keboola.com/admin/projects/258/orchestrations/298028864/tasks

**Comment by Halama** [comment]
Zavírám a dáme kdyžtak reopen pokud se to objeví znovu v nějakém jiném regionu.
